# Generated by Django 5.1 on 2024-08-28 10:34

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('corporate_date', django_jalali.db.models.jDateField()),
                ('program_name', models.CharField(max_length=100)),
            ],
        ),
    ]
