# Generated by Django 5.1 on 2024-09-01 13:30

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_city_province_customer_city_city_province_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'شهر', 'verbose_name_plural': 'شهرها'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'مشتری', 'verbose_name_plural': 'مشتریان'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'استان', 'verbose_name_plural': 'استان\u200cها'},
        ),
        migrations.AlterField(
            model_name='city',
            name='latitude',
            field=models.CharField(max_length=20, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.CharField(max_length=20, verbose_name='طول جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام شهر'),
        ),
        migrations.AlterField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='customer.province', verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.city', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='corporate_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ همکاری'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام مشتری'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='program_name',
            field=models.CharField(max_length=100, verbose_name='نام برنامه'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.province', verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام استان'),
        ),
    ]
