# Generated by Django 5.1 on 2024-10-14 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customertitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertitle',
            name='work_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='مشتریان'),
        ),
    ]
