# Generated by Django 5.1 on 2024-10-14 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customertitle_work_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customertitle',
            old_name='work_field',
            new_name='customer',
        ),
    ]
