# Generated by Django 5.1 on 2024-09-09 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_main_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='detail_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='متن جزیات'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='product.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_text',
            field=models.TextField(blank=True, verbose_name='ویژگی'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='product.product', verbose_name='محصول'),
        ),
    ]
