# Generated by Django 5.1 on 2024-09-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_detail_detail_text_alter_detail_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_count_in_main',
            field=models.BooleanField(default=False, help_text='در صورت روشن بودن این فیلد در پایین صفحه ی خانه تعداد محصولات این دسته بندی نمایش داده میشود ', verbose_name='نمایش در صفحه ی اصلی'),
        ),
    ]
