# Generated by Django 5.1 on 2024-10-09 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_category_show_count_in_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_slides/', verbose_name='تصویر')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='product.product', verbose_name='محصول')),
            ],
        ),
    ]
