# Generated by Django 5.1 on 2024-10-09 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_slide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='main_photo',
            new_name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_icon_photo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='secend_photo',
        ),
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_text', models.CharField(blank=True, max_length=100, verbose_name='قابلیت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'قابلیت',
                'verbose_name_plural': 'قابلیت ها',
            },
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
