# Generated by Django 5.1 on 2024-10-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_main_photo_product_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_icon_photo',
            field=models.ImageField(default='', upload_to='fproduct/icons', verbose_name='عکس ایکون لیست محصولات'),
            preserve_default=False,
        ),
    ]
