# Generated by Django 5.1 on 2024-09-01 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'گواهینامه', 'verbose_name_plural': 'گواهینامه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'مدیر', 'verbose_name_plural': 'مدیران'},
        ),
        migrations.AlterModelOptions(
            name='workfield',
            options={'verbose_name': 'حوزه کاری', 'verbose_name_plural': 'حوزه\u200cهای کاری'},
        ),
        migrations.AlterModelOptions(
            name='worktags',
            options={'verbose_name': 'برچسب کاری', 'verbose_name_plural': 'برچسب\u200cهای کاری'},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=models.TextField(verbose_name='توضیحات گواهینامه'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(upload_to='photos/certificates/%Y/%m/%d/', verbose_name='عکس گواهینامه'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان گواهینامه'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام مدیر'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='ordering',
            field=models.PositiveIntegerField(unique=True, verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='workfield',
            name='description',
            field=models.TextField(verbose_name='توضیحات حوزه'),
        ),
        migrations.AlterField(
            model_name='workfield',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.worktags', verbose_name='برچسب\u200cها'),
        ),
        migrations.AlterField(
            model_name='workfield',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان حوزه'),
        ),
        migrations.AlterField(
            model_name='worktags',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
    ]
