# Generated by Django 5.1 on 2024-09-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_certificate_options_alter_manager_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soical', models.CharField(choices=[('اینستاگرام', 'instagram'), ('تلگرام', 'telegram'), ('واتساپ', 'whatsapp'), ('تویتر', 'twitter')], max_length=100, unique=True)),
                ('link', models.URLField()),
            ],
        ),
    ]
