# Generated by Django 5.1 on 2024-09-06 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_soical'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soical',
            options={'verbose_name': 'شبکه ی اجتماعی', 'verbose_name_plural': 'شبکه های اجتماعی'},
        ),
    ]
