# Generated by Django 5.1 on 2024-09-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_soical_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='workfield',
            name='ordering',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='ترتیب'),
            preserve_default=False,
        ),
    ]
