# Generated by Django 5.1 on 2024-09-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_workfield_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('ordering', models.PositiveIntegerField(unique=True, verbose_name='ترتیب')),
            ],
        ),
        migrations.CreateModel(
            name='NumberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('ordering', models.PositiveIntegerField(unique=True, verbose_name='ترتیب')),
            ],
        ),
    ]
