# Generated by Django 5.1 on 2024-09-24 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_emailmodel_numbermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_us/', verbose_name='تصویر')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='AboutProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='تعداد پروژه\u200cها')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان پروژه\u200cها')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='about.aboutus')),
            ],
        ),
        migrations.CreateModel(
            name='HeroLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=100, verbose_name='متن جایگزین لوگو')),
                ('link', models.URLField(verbose_name='لینک لوگو')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logo', to='about.herosection')),
            ],
        ),
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=100, verbose_name='متن جایگزین')),
                ('link', models.URLField(verbose_name='لینک تصویر')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='about.herosection')),
            ],
        ),
        migrations.CreateModel(
            name='HeroButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان دکمه')),
                ('link', models.URLField(verbose_name='لینک دکمه')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='about.herosection')),
            ],
        ),
    ]
