# Generated by Django 5.1 on 2024-09-24 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_aboutus_herosection_aboutproject_herologo_heroimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('subtitle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DemoForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('demo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.demo')),
            ],
        ),
    ]
