# Generated by Django 5.1 on 2024-09-24 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_footer_hero_alter_aboutproject_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroimage',
            name='link',
            field=models.FileField(upload_to='photos/images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='herologo',
            name='link',
            field=models.FileField(upload_to=''),
        ),
        migrations.CreateModel(
            name='HeroBodyLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=255)),
                ('link', models.FileField(upload_to='')),
                ('hero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bodylogo', to='about.hero')),
            ],
        ),
    ]
