# Generated by Django 5.1 on 2024-10-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_alter_heroimage_link_alter_herologo_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workfield',
            name='tags',
        ),
        migrations.AddField(
            model_name='workfield',
            name='tags',
            field=models.ManyToManyField(to='about.worktags', verbose_name='برچسب\u200cها'),
        ),
    ]
