# Generated by Django 5.1 on 2024-10-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_remove_workfield_tags_workfield_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktags',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
