# Generated by Django 5.1 on 2024-10-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_worktags_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='workfield',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
