# Generated by Django 5.1 on 2024-10-03 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0013_workfield_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='photo',
            new_name='image',
        ),
    ]
