# Generated by Django 5.1 on 2024-10-11 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0014_rename_photo_manager_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.certificate')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('managers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.manager')),
            ],
        ),
        migrations.CreateModel(
            name='WorkTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('work_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.workfield')),
            ],
        ),
    ]
