# Generated by Django 5.1 on 2024-10-12 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0015_certificatetitle_managertitle_worktitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutproject',
            options={'verbose_name': 'پروژه درباره ما', 'verbose_name_plural': 'پروژه\u200cهای درباره ما'},
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'درباره ما', 'verbose_name_plural': 'درباره ما'},
        ),
        migrations.AlterModelOptions(
            name='certificatetitle',
            options={'verbose_name': 'عنوان گواهینامه', 'verbose_name_plural': 'عناوین گواهینامه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='demo',
            options={'verbose_name': 'دمو', 'verbose_name_plural': 'دموها'},
        ),
        migrations.AlterModelOptions(
            name='demoform',
            options={'verbose_name': 'فرم دمو', 'verbose_name_plural': 'فرم\u200cهای دمو'},
        ),
        migrations.AlterModelOptions(
            name='emailmodel',
            options={'verbose_name': 'مدل ایمیل', 'verbose_name_plural': 'مدل\u200cهای ایمیل'},
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'فوتر', 'verbose_name_plural': 'فوترها'},
        ),
        migrations.AlterModelOptions(
            name='footeremail',
            options={'verbose_name': 'ایمیل فوتر', 'verbose_name_plural': 'ایمیل\u200cهای فوتر'},
        ),
        migrations.AlterModelOptions(
            name='footerphone',
            options={'verbose_name': 'تلفن فوتر', 'verbose_name_plural': 'تلفن\u200cهای فوتر'},
        ),
        migrations.AlterModelOptions(
            name='footersocial',
            options={'verbose_name': 'شبکه اجتماعی فوتر', 'verbose_name_plural': 'شبکه\u200cهای اجتماعی فوتر'},
        ),
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name': 'هیرو', 'verbose_name_plural': 'هیروها'},
        ),
        migrations.AlterModelOptions(
            name='herobodylogo',
            options={'verbose_name': 'لوگو بدن هیرو', 'verbose_name_plural': 'لوگوهای بدن هیرو'},
        ),
        migrations.AlterModelOptions(
            name='herobutton',
            options={'verbose_name': 'دکمه هیرو', 'verbose_name_plural': 'دکمه\u200cهای هیرو'},
        ),
        migrations.AlterModelOptions(
            name='heroimage',
            options={'verbose_name': 'تصویر هیرو', 'verbose_name_plural': 'تصاویر هیرو'},
        ),
        migrations.AlterModelOptions(
            name='herologo',
            options={'verbose_name': 'لوگو هیرو', 'verbose_name_plural': 'لوگوهای هیرو'},
        ),
        migrations.AlterModelOptions(
            name='managertitle',
            options={'verbose_name': 'عنوان مدیر', 'verbose_name_plural': 'عناوین مدیران'},
        ),
        migrations.AlterModelOptions(
            name='numbermodel',
            options={'verbose_name': 'مدل شماره', 'verbose_name_plural': 'مدل\u200cهای شماره'},
        ),
        migrations.AlterModelOptions(
            name='soical',
            options={'verbose_name': 'شبکه اجتماعی', 'verbose_name_plural': 'شبکه\u200cهای اجتماعی'},
        ),
        migrations.AlterModelOptions(
            name='worktitle',
            options={'verbose_name': 'عنوان کاری', 'verbose_name_plural': 'عناوین کاری'},
        ),
        migrations.RemoveField(
            model_name='aboutproject',
            name='count',
        ),
        migrations.AddField(
            model_name='aboutproject',
            name='description',
            field=models.TextField(default='', verbose_name='توضیحات پروژه'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutproject',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='about.aboutus', verbose_name='درباره ما'),
        ),
        migrations.AlterField(
            model_name='aboutproject',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان پروژه'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(upload_to='about/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='certificatetitle',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.certificate', verbose_name='گواهینامه'),
        ),
        migrations.AlterField(
            model_name='certificatetitle',
            name='description',
            field=models.TextField(verbose_name='توضیحات گواهینامه'),
        ),
        migrations.AlterField(
            model_name='certificatetitle',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان گواهینامه'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='image',
            field=models.ImageField(upload_to='demo/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='subtitle',
            field=models.CharField(max_length=255, verbose_name='زیرعنوان'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='demoform',
            name='demo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form', to='about.demo', verbose_name='دمو'),
        ),
        migrations.AlterField(
            model_name='demoform',
            name='description',
            field=models.TextField(verbose_name='توضیحات فرم'),
        ),
        migrations.AlterField(
            model_name='demoform',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان فرم'),
        ),
        migrations.AlterField(
            model_name='emailmodel',
            name='email',
            field=models.CharField(max_length=100, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='address',
            field=models.CharField(max_length=255, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='copyright',
            field=models.CharField(max_length=255, verbose_name='کپی رایت'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='footeremail',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='footeremail',
            name='footer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='about.footer', verbose_name='فوتر'),
        ),
        migrations.AlterField(
            model_name='footerphone',
            name='footer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='about.footer', verbose_name='فوتر'),
        ),
        migrations.AlterField(
            model_name='footerphone',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='footersocial',
            name='alt',
            field=models.CharField(max_length=100, verbose_name='متن جایگزین'),
        ),
        migrations.AlterField(
            model_name='footersocial',
            name='footer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='about.footer', verbose_name='فوتر'),
        ),
        migrations.AlterField(
            model_name='footersocial',
            name='icon',
            field=models.CharField(max_length=100, verbose_name='آیکون'),
        ),
        migrations.AlterField(
            model_name='footersocial',
            name='link',
            field=models.URLField(verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='herobodylogo',
            name='alt',
            field=models.CharField(max_length=255, verbose_name='متن جایگزین'),
        ),
        migrations.AlterField(
            model_name='herobodylogo',
            name='hero',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bodylogo', to='about.hero', verbose_name='هیرو'),
        ),
        migrations.AlterField(
            model_name='herobodylogo',
            name='link',
            field=models.FileField(upload_to='', verbose_name='لینک لوگو بدن'),
        ),
        migrations.AlterField(
            model_name='herobutton',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='about.hero', verbose_name='هیرو'),
        ),
        migrations.AlterField(
            model_name='herobutton',
            name='link',
            field=models.URLField(verbose_name='لینک دکمه'),
        ),
        migrations.AlterField(
            model_name='herobutton',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان دکمه'),
        ),
        migrations.AlterField(
            model_name='heroimage',
            name='alt',
            field=models.CharField(max_length=255, verbose_name='متن جایگزین'),
        ),
        migrations.AlterField(
            model_name='heroimage',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='about.hero', verbose_name='هیرو'),
        ),
        migrations.AlterField(
            model_name='heroimage',
            name='link',
            field=models.FileField(upload_to='photos/images/%Y/%m/%d/', verbose_name='لینک تصویر'),
        ),
        migrations.AlterField(
            model_name='herologo',
            name='alt',
            field=models.CharField(max_length=255, verbose_name='متن جایگزین'),
        ),
        migrations.AlterField(
            model_name='herologo',
            name='hero',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logo', to='about.hero', verbose_name='هیرو'),
        ),
        migrations.AlterField(
            model_name='herologo',
            name='link',
            field=models.FileField(upload_to='', verbose_name='لینک لوگو'),
        ),
        migrations.AlterField(
            model_name='managertitle',
            name='description',
            field=models.TextField(verbose_name='توضیحات مدیر'),
        ),
        migrations.AlterField(
            model_name='managertitle',
            name='managers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.manager', verbose_name='مدیر'),
        ),
        migrations.AlterField(
            model_name='managertitle',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان مدیر'),
        ),
        migrations.AlterField(
            model_name='numbermodel',
            name='number',
            field=models.CharField(max_length=30, verbose_name='شماره'),
        ),
        migrations.AlterField(
            model_name='soical',
            name='link',
            field=models.URLField(verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='soical',
            name='soical',
            field=models.CharField(choices=[('اینستاگرام', 'instagram'), ('تلگرام', 'telegram'), ('واتساپ', 'whatsapp'), ('تویتر', 'twitter')], max_length=100, unique=True, verbose_name='شبکه اجتماعی'),
        ),
        migrations.AlterField(
            model_name='workfield',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='worktags',
            name='link',
            field=models.URLField(verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='worktitle',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='worktitle',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='worktitle',
            name='work_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.workfield', verbose_name='حوزه کاری'),
        ),
    ]
