# Generated by Django 5.1 on 2024-10-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0016_alter_aboutproject_options_alter_aboutus_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailModel',
        ),
        migrations.DeleteModel(
            name='NumberModel',
        ),
        migrations.DeleteModel(
            name='Soical',
        ),
        migrations.RemoveField(
            model_name='footersocial',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='footersocial',
            name='icon',
        ),
        migrations.AddField(
            model_name='footersocial',
            name='soical',
            field=models.CharField(choices=[('اینستاگرام', 'instagram'), ('تلگرام', 'telegram'), ('واتساپ', 'whatsapp'), ('تویتر', 'twitter')], default='', max_length=100, unique=True, verbose_name='شبکه اجتماعی'),
            preserve_default=False,
        ),
    ]
