# Generated by Django 5.1 on 2024-10-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0017_delete_emailmodel_delete_numbermodel_delete_soical_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'لینک هدر',
                'verbose_name_plural': 'لینک های هدر',
            },
        ),
    ]
