# Generated by Django 5.1 on 2024-10-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0018_headerlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTagsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('main_page', 'صفحه اصلی'), ('customer', 'صفحه ی مشتریان')], max_length=20)),
                ('meta_description', models.TextField(verbose_name='متا تگ دسکریپشن')),
                ('meta_keyword', models.TextField(help_text='لطفا با کاما وارد کنید', verbose_name='متا تگ کیورد')),
            ],
            options={
                'verbose_name': 'متا تگ های صفحات',
                'verbose_name_plural': 'متا تگ صفحات',
            },
        ),
    ]
