# Generated by Django 5.1 on 2024-10-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0019_metatagspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='metatagspage',
            name='meta_title',
            field=models.TextField(default='', verbose_name='متا تگ عنوان'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metatagspage',
            name='page',
            field=models.CharField(choices=[('main_page', 'صفحه اصلی'), ('customer', 'صفحه ی مشتریان')], max_length=20, unique=True),
        ),
    ]
