# Generated by Django 5.1 on 2024-10-11 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_requestdemo_module'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestdemo',
            old_name='module',
            new_name='module_name',
        ),
    ]
