# Generated by Django 5.1 on 2024-10-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_endpointsendcontactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndPointSendRequestDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_link', models.URLField(verbose_name='لینک پست درخواست دمو')),
                ('full_name', models.BooleanField(help_text='ارسال با کلید full_name', verbose_name='ارسال نام')),
                ('email', models.BooleanField(help_text='ارسال با کلید email', verbose_name='ارسال ایمیل')),
                ('phone_number', models.BooleanField(help_text='ارسال با کلید phone_number', verbose_name='ارسال شماره تلفن')),
                ('company_name', models.BooleanField(help_text='ارسال با کلید company_name', verbose_name='ارسال نام شرکت')),
                ('message', models.BooleanField(help_text='ارسال با کلید message', verbose_name='ارسال پیام')),
                ('module_name', models.BooleanField(help_text='ارسال با کلید module_name', verbose_name='ارسال نام ماژول')),
                ('requested_at', models.BooleanField(help_text='ارسال با کلید requested_at', verbose_name='ارسال تاریخ درخواست')),
            ],
            options={
                'verbose_name': 'لینک پست درخواست دمو',
                'verbose_name_plural': 'لینک های پست درخواست دمو',
            },
        ),
        migrations.AlterField(
            model_name='endpointsendcontactus',
            name='contacted_at',
            field=models.BooleanField(help_text='ارسال با کلید contacted_at', verbose_name='ارسال تاریخ تماس'),
        ),
        migrations.AlterField(
            model_name='endpointsendcontactus',
            name='email',
            field=models.BooleanField(help_text='ارسال با کلید email', verbose_name='ارسال ایمیل'),
        ),
        migrations.AlterField(
            model_name='endpointsendcontactus',
            name='full_name',
            field=models.BooleanField(help_text='ارسال با کلید full_name', verbose_name='ارسال نام'),
        ),
        migrations.AlterField(
            model_name='endpointsendcontactus',
            name='message',
            field=models.BooleanField(help_text='ارسال با کلید message', verbose_name='ارسال پیام'),
        ),
        migrations.AlterField(
            model_name='endpointsendcontactus',
            name='request_link',
            field=models.URLField(verbose_name='لینک پست ارتباط با ما'),
        ),
        migrations.AlterField(
            model_name='endpointsendcontactus',
            name='subject',
            field=models.BooleanField(help_text='ارسال با کلید subject', verbose_name='ارسال موضوع'),
        ),
    ]
