# Generated by Django 5.1 on 2024-10-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_endpointsendrequestdemo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(max_length=10)),
                ('response', models.TextField()),
                ('exception', models.TextField()),
            ],
        ),
    ]
