# Generated by Django 5.1 on 2024-10-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_logtickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='logtickets',
            name='request_body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
