# Generated by Django 5.1 on 2024-10-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_logtickets_request_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(blank=True, max_length=10, null=True)),
                ('request_body', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('exception', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LogTickets',
        ),
    ]
